service: serverless-security

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  logRetentionInDays: 7
  memorySize: 128
  versionFunctions: false

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  alert:
    handler: bin/main
    environment:
      INCOMING_WEBHOOK_URL: ${ssm:/slack/incoming_webhook_url} # 末尾に「~true」は不要
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.securityhub'
            detail-type:
              - 'Security Hub Findings - Imported'
            detail:
              findings:
                Severity:
                  Label:
                    - 'CRITICAL'
                    - 'HIGH'
                    - 'MEDIUM'
                # サービスを限定する場合
#                ProductFields:
#                  'aws/securityhub/ProductName':
#                    - 'GuardDuty'
#                    - 'IAM Access Analyzer'
