service: serverless-budgets

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  logRetentionInDays: 7
  memorySize: 128
  versionFunctions: false
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'budgets:ViewBudget'
      Resource: '*'

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  slack:
    handler: bin/main
    environment:
      INCOMING_WEBHOOK_URL: ${ssm:/slack/incoming_webhook_url} # 末尾に「~true」は不要
    events:
      - schedule: cron(30 22 * * ? *) # UTC
